/**
 * Danh sách categories chuẩn trong hệ thống
 * Đồng bộ với categories được sử dụng trong Frontend Flutter
 */
export const CATEGORIES = {
  // Thu nhập
  INCOME: 'income',

  // Chi tiêu
  FOOD: 'food',
  TRANSPORTATION: 'transportation',
  ENTERTAINMENT: 'entertainment',
  SHOPPING: 'shopping',
  HEALTH: 'health',
  EDUCATION: 'education',
  UTILITIES: 'utilities',
  HOME: 'home',
  PERSONAL: 'personal',
  TRAVEL: 'travel',
  INVESTMENT: 'investment',
  FAMILY: 'family',
  HOUSEWARE: 'houseware',
  DONATION: 'donation',
  CHARITY: 'charity',
  OTHER: 'other',
} as const;

export type CategoryType = (typeof CATEGORIES)[keyof typeof CATEGORIES];

/**
 * Keyword mapping cho từng category
 * Sử dụng để bootstrap classifier trước khi có ML model
 */
export const CATEGORY_KEYWORDS: Record<CategoryType, string[]> = {
  [CATEGORIES.INCOME]: [
    // Tiếng Việt
    'lương',
    'thưởng',
    'thu nhập',
    'tiền lãi',
    'cổ tức',
    'nhận tiền',
    'thu',
    'trả lương',
    'được trả',
    'kiếm được',
    'tiền về',
    'hoàn tiền',
    'chuyển khoản đến',
    'nhận chuyển khoản',
    'tiền thưởng',
    'hoa hồng',
    'commission',
    'tiền công',
    'tiền làm thêm',
    'overtime',
    // Tiếng Anh
    'salary',
    'bonus',
    'income',
    'interest',
    'dividend',
    'receive',
    'earn',
    'paid',
    'payment received',
    'refund',
    'cashback',
    'rebate',
  ],

  [CATEGORIES.FOOD]: [
    // Tiếng Việt - Đồ ăn
    'ăn',
    'cơm',
    'phở',
    'bún',
    'bánh',
    'mì',
    'quán',
    'nhà hàng',
    'cafe',
    'cà phê',
    'trà sữa',
    'ăn sáng',
    'ăn trưa',
    'ăn tối',
    'buffet',
    'bữa ăn',
    'gọi món',
    'ship đồ ăn',
    'grabfood',
    'shopeefood',
    'beeFood',
    'gofood',
    'food',
    'order',
    'đồ ăn',
    'thức ăn',
    'lẩu',
    'nướng',
    'gà rán',
    'pizza',
    'burger',
    'sushi',
    'highlands',
    'starbucks',
    'kfc',
    'lotteria',
    'jollibee',
    // Đồ uống
    'coca',
    'pepsi',
    'sprite',
    'bia',
    'rượu',
    'nước ngọt',
    'soda',
    'tonic',
    'nước ép',
    'sinh tố',
    'smoothie',
    'trà',
    'tea',
    'coffee',
    // Cửa hàng/vendor
    'coopmart',
    'vinmart',
    'circle k',
    'ministop',
    'gs25',
    'family mart',
    'bách hóa xanh',
    'big c',
    'lotte mart',
    'aeon',
    // Món ăn cụ thể
    'bò',
    'gà',
    'heo',
    'cá',
    'tôm',
    'cua',
    'mực',
    'rau',
    'xôi',
    'cháo',
    'hủ tiếu',
    'bánh cuốn',
    'bánh xèo',
    'gỏi cuốn',
    'chả giò',
    'nem',
  ],

  [CATEGORIES.TRANSPORTATION]: [
    // Tiếng Việt - Đi lại
    'grab',
    'uber',
    'be',
    'taxi',
    'xe ôm',
    'xe buýt',
    'bus',
    'xăng',
    'dầu',
    'đổ xăng',
    'xe',
    'gửi xe',
    'đậu xe',
    'parking',
    'vé xe',
    'vé tàu',
    'đi lại',
    'di chuyển',
    'đăng kiểm',
    'bảo hiểm xe',
    'phí cầu đường',
    'toll',
    'BOT',
    'cao tốc',
    'expressway',
    // Apps
    'grabcar',
    'grabbike',
    'be bike',
    'be car',
    'gojek',
    'maxim',
    'xanh sm',
    // Phương tiện
    'ô tô',
    'xe máy',
    'xe đạp',
    'metro',
    'tàu điện',
    'bảo dưỡng xe',
    'sửa xe',
    'rửa xe',
  ],

  [CATEGORIES.TRAVEL]: [
    // Du lịch
    'du lịch',
    'travel',
    'tour',
    'khách sạn',
    'hotel',
    'resort',
    'booking',
    'airbnb',
    'agoda',
    'traveloka',
    'expedia',
    'vé máy bay',
    'flight',
    'bay',
    'tàu',
    'máy bay',
    'vietnam airlines',
    'vietjet',
    'bamboo airways',
    'pacific airlines',
    'jetstar',
    // Địa điểm du lịch
    'đà lạt',
    'nha trang',
    'phú quốc',
    'đà nẵng',
    'hội an',
    'huế',
    'sapa',
    'hạ long',
    'mũi né',
    'côn đảo',
    // Chi phí du lịch
    'visa',
    'passport',
    'hộ chiếu',
    'tour guide',
    'hướng dẫn viên',
    'vé tham quan',
    'entrance fee',
    'phí vào cửa',
  ],

  [CATEGORIES.ENTERTAINMENT]: [
    // Tiếng Việt - Giải trí
    'vui chơi',
    'giải trí',
    'xem phim',
    'cinema',
    'rap',
    'cgv',
    'lotte',
    'galaxy',
    'game',
    'netflix',
    'spotify',
    'youtube premium',
    'karaoke',
    'bar',
    'club',
    'vé',
    'ticket',
    'concert',
    'sự kiện',
    'event',
    'show',
    'biểu diễn',
    'spa',
    'massage',
    // Streaming & Gaming
    'apple music',
    'steam',
    'playstation',
    'xbox',
    'nintendo',
    'pubg',
    'mobile legends',
    'liên quân',
    'free fire',
    // Địa điểm giải trí
    'vinwonders',
    'bảo tàng',
    'museum',
    'công viên',
    'park',
    'zoo',
    'thủy cung',
    'aquarium',
    'đầm sen',
    'suối tiên',
  ],

  [CATEGORIES.SHOPPING]: [
    // Tiếng Việt - Mua sắm quần áo, thời trang
    'mua',
    'shopping',
    'quần áo',
    'giày',
    'dép',
    'áo',
    'thời trang',
    'fashion',
    'phụ kiện',
    'túi',
    'balo',
    'ví',
    'mỹ phẩm',
    'cosmetic',
    'nước hoa',
    'perfume',
    'son',
    'lipstick',
    'lazada',
    'shopee',
    'tiki',
    'sendo',
    'zalora',
    'uniqlo',
    'zara',
    'h&m',
    'adidas',
    'nike',
    'converse',
    // Thêm nhiều keywords
    'quần',
    'váy',
    'đầm',
    'jacket',
    'áo khoác',
    'đồng hồ',
    'watch',
    'kính mát',
    'sunglasses',
    'trang sức',
    'jewelry',
    'nhẫn',
    'vòng',
    'dây chuyền',
    // E-commerce
    'amazon',
    'ebay',
    'aliexpress',
    'taobao',
  ],

  [CATEGORIES.HOUSEWARE]: [
    // Đồ gia dụng, điện tử
    'điện thoại',
    'laptop',
    'macbook',
    'iphone',
    'samsung',
    'điện tử',
    'electronics',
    'thegioididong',
    'fpt shop',
    // Điện máy
    'điện máy xanh',
    'nguyễn kim',
    'pico',
    'mediamart',
    'máy tính',
    'computer',
    'tablet',
    'ipad',
    'airpods',
    'tai nghe',
    'headphone',
    // Đồ gia dụng
    'nồi',
    'chảo',
    'bát đĩa',
    'dao',
    'thớt',
    'ấm đun',
    'bình giữ nhiệt',
    'máy xay',
    'máy ép',
    'nồi chiên',
    'air fryer',
    'máy hút bụi',
    'robot hút bụi',
    'máy lọc không khí',
    'máy sấy tóc',
    'bàn là',
    'bàn ủi',
    // Thiết bị nhà bếp
    'lò nướng',
    'oven',
    'máy pha cà phê',
    'coffee maker',
    'máy làm bánh',
  ],

  [CATEGORIES.HEALTH]: [
    // Tiếng Việt - Sức khỏe
    'bác sĩ',
    'doctor',
    'khám bệnh',
    'bệnh viện',
    'hospital',
    'phòng khám',
    'clinic',
    'thuốc',
    'medicine',
    'nhà thuốc',
    'pharmacy',
    'pharmacity',
    'long châu',
    'an khang',
    'xét nghiệm',
    'test',
    'chích ngừa',
    'vaccine',
    'tiêm',
    'răng',
    'nha khoa',
    'dental',
    'mắt',
    'kính',
    'glasses',
    'bảo hiểm y tế',
    'health insurance',
    // Thêm keywords
    'khám tổng quát',
    'checkup',
    'siêu âm',
    'x-ray',
    'xquang',
    'CT scan',
    'MRI',
    'chữa bệnh',
    'điều trị',
    'treatment',
    'phẫu thuật',
    'surgery',
    'cấp cứu',
    'emergency',
    'vitamin',
    'thực phẩm chức năng',
    'supplement',
    // Bệnh viện cụ thể
    'vinmec',
    'fv hospital',
    'chợ rẫy',
    'bạch mai',
    '115',
  ],

  [CATEGORIES.EDUCATION]: [
    // Tiếng Việt - Giáo dục
    'học',
    'study',
    'học phí',
    'tuition',
    'trường',
    'school',
    'khóa học',
    'course',
    'lớp',
    'class',
    'giáo trình',
    'sách',
    'book',
    'udemy',
    'coursera',
    'edx',
    'skillshare',
    'ielts',
    'toeic',
    'tiếng anh',
    'english',
    'ngoại ngữ',
    'đào tạo',
    'training',
    'workshop',
    'seminar',
    'hội thảo',
    // Thêm keywords
    'đại học',
    'university',
    'cao đẳng',
    'college',
    'trung tâm',
    'center',
    'gia sư',
    'tutor',
    'luyện thi',
    'exam prep',
    'chứng chỉ',
    'certificate',
    'bằng cấp',
    'degree',
    'tốt nghiệp',
    'graduation',
    // Platforms
    'duolingo',
    'linkedin learning',
    'masterclass',
    'pluralsight',
    'codecademy',
    // Ngôn ngữ
    'tiếng nhật',
    'japanese',
    'tiếng hàn',
    'korean',
    'tiếng trung',
    'chinese',
  ],

  [CATEGORIES.UTILITIES]: [
    // Tiếng Việt - Hóa đơn định kỳ
    'hóa đơn',
    'bill',
    'điện',
    'nước',
    'electricity',
    'water',
    'internet',
    'wifi',
    'điện thoại',
    'phone bill',
    'mobile',
    'viettel',
    'mobifone',
    'vinaphone',
    'vnpt',
    'fpt',
    'cáp',
    'cable',
    'truyền hình',
    'tv',
    'phí',
    'fee',
    'service charge',
    'phí dịch vụ',
    'phí quản lý',
    // Thêm keywords
    'tiền điện',
    'tiền nước',
    'tiền mạng',
    'cước điện thoại',
    'gói cước',
    'data',
    '3g',
    '4g',
    '5g',
    'subscription',
    'đăng ký',
    'gia hạn',
    'renew',
    // Dịch vụ streaming
    'netflix',
    'spotify',
    'disney+',
    'hbo',
    'apple tv',
    'youtube music',
    'amazon prime',
    // Phí khác
    'phí chung cư',
    'phí bảo trì',
    'maintenance fee',
  ],

  [CATEGORIES.HOME]: [
    // Tiếng Việt - Nhà ở
    'nhà',
    'house',
    'rent',
    'thuê nhà',
    'tiền nhà',
    'tiền trọ',
    'phòng trọ',
    'apartment',
    'chung cư',
    'căn hộ',
    'sửa chữa',
    'repair',
    'bảo trì',
    'maintenance',
    'sơn',
    'nội thất',
    'furniture',
    'đồ dùng',
    'ikea',
    'nhà xinh',
    'đèn',
    'quạt',
    'máy lạnh',
    'tủ',
    'giường',
    'bàn',
    'ghế',
    // Thêm keywords
    'điều hòa',
    'air conditioner',
    'tủ lạnh',
    'refrigerator',
    'máy giặt',
    'washing machine',
    'lò vi sóng',
    'microwave',
    'bếp',
    'kitchen',
    'nồi cơm',
    'rice cooker',
    'bình nóng lạnh',
    'water heater',
    'rèm',
    'curtain',
    'thảm',
    'carpet',
    'gương',
    'mirror',
    // Cửa hàng nội thất
    'uma',
    'index living mall',
    'an cường',
    'hòa phát',
    // Sửa chữa
    'thợ điện',
    'electrician',
    'thợ nước',
    'plumber',
    'dọn nhà',
    'cleaning',
    'giúp việc',
    'maid',
  ],

  [CATEGORIES.PERSONAL]: [
    // Tiếng Việt - Cá nhân
    'cắt tóc',
    'haircut',
    'salon',
    'nail',
    'móng',
    'wax',
    'gym',
    'fitness',
    'yoga',
    'thể thao',
    'sport',
    'bơi',
    'quà',
    'gift',
    'tặng',
    'birthday',
    'sinh nhật',
    'kỷ niệm',
    'anniversary',
    // Thêm keywords
    'làm đẹp',
    'beauty',
    'skincare',
    'chăm sóc da',
    'facial',
    'tẩy lông',
    'laser',
    'thẩm mỹ',
    'aesthetic',
    // Phòng gym
    'california fitness',
    'citigym',
    'elite fitness',
    // Quà tặng
    'valentine',
    'christmas',
    'giáng sinh',
    'tết',
    'new year',
    'quà cưới',
    'wedding gift',
    // Thể thao
    'tennis',
    'badminton',
    'cầu lông',
    'bóng đá',
    'football',
    'golf',
    'running',
    'chạy bộ',
  ],

  [CATEGORIES.FAMILY]: [
    // Chi phí gia đình
    'gia đình',
    'family',
    'con',
    'children',
    'kids',
    'bé',
    'baby',
    'trẻ em',
    'bỉm',
    'tã',
    'diaper',
    'sữa bột',
    'formula',
    'đồ chơi',
    'toy',
    'trường mầm non',
    'kindergarten',
    'nhà trẻ',
    'daycare',
    'bố mẹ',
    'parents',
    'ông bà',
    'grandparents',
    'tiền chu cấp',
    'biếu',
    'hiếu hỉ',
    'đám cưới',
    'wedding',
    'đám tang',
    'funeral',
    'giỗ',
    'lễ',
    'thăm nom',
    'visit',
    'nuôi con',
    'child care',
    'học phí con',
    'tiền tiêu vặt',
    'pocket money',
  ],

  [CATEGORIES.INVESTMENT]: [
    // Đầu tư
    'đầu tư',
    'investment',
    'invest',
    'cổ phiếu',
    'stock',
    'chứng khoán',
    'securities',
    'trái phiếu',
    'bond',
    'quỹ',
    'fund',
    'mutual fund',
    'etf',
    'crypto',
    'bitcoin',
    'ethereum',
    'tiền điện tử',
    'cryptocurrency',
    'vàng',
    'gold',
    'bất động sản',
    'real estate',
    'bđs',
    'đất',
    'land',
    'chung cư đầu tư',
    'tiết kiệm',
    'saving',
    'gửi tiết kiệm',
    'lãi suất',
    'interest rate',
    'vingroup',
    'vcb',
    'vietcombank',
    'techcombank',
    'mbs',
    'ssi',
    'vnds',
    'fpts',
    'vndirect',
    'binance',
    'coinbase',
  ],

  [CATEGORIES.DONATION]: [
    // Quyên góp
    'quyên góp',
    'donation',
    'donate',
    'ủng hộ',
    'support',
    'giúp đỡ',
    'cứu trợ',
    'relief',
    'thiên tai',
    'disaster',
    'lũ lụt',
    'flood',
    'bão',
    'storm',
    'hạn hán',
    'drought',
    'quỹ từ thiện',
    'charity fund',
    'red cross',
    'hội chữ thập đỏ',
    'unicef',
    'wwf',
    'gây quỹ',
    'fundraising',
    'crowdfunding',
  ],

  [CATEGORIES.CHARITY]: [
    // Từ thiện
    'từ thiện',
    'charity',
    'thiện nguyện',
    'volunteer',
    'tình nguyện',
    'giúp người nghèo',
    'help the poor',
    'trẻ mồ côi',
    'orphan',
    'người già',
    'elderly',
    'người khuyết tật',
    'disabled',
    'nhà tình thương',
    'mái ấm',
    'shelter',
    'cô nhi viện',
    'orphanage',
    'viện dưỡng lão',
    'nursing home',
    'cho đi',
    'give',
    'giving',
    'phát quà',
    'tặng quà từ thiện',
  ],

  [CATEGORIES.OTHER]: [
    // Fallback
    'khác',
    'other',
    'misc',
    'miscellaneous',
    'other expenses',
    'chi phí khác',
    'phí khác',
    'tiền khác',
  ],
};

/**
 * Danh sách tất cả categories để suggest cho user
 */
export const ALL_CATEGORIES: CategoryType[] = Object.values(CATEGORIES);

/**
 * Categories mặc định khi không predict được
 */
export const DEFAULT_CATEGORY: CategoryType = CATEGORIES.OTHER;
